language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install: 
    - pip install .
    - pip install python-coveralls gunicorn bottle
script: coverage run tests/testall.py
after_success:
  - coveralls
